user = User.create!(email: "bob@bob.com", password: "password")

Tag.create!([
  {tag: "leather", type_id: 1},
  {tag: "resin/pine", type_id: 3},
  {tag: "vanilla", type_id: 4},
  {tag: "menthol", type_id: 3},
  {tag: "earth", type_id: 3},
  {tag: "mushroom", type_id: 3},
  {tag: "cedar", type_id: 3},
  {tag: "graphite", type_id: 3},
  {tag: "baking spices", type_id: 4},
  {tag: "butter", type_id: 4},
  {tag: "ginger", type_id: 3},
  {tag: "almond", type_id: 3},
  {tag: "toast", type_id: 1},
  {tag: "mocha", type_id: 4},
  {tag: "pepper", type_id: 1},
  {tag: "bell pepper", type_id: 1},
  {tag: "blackberry jam", type_id: 4},
  {tag: "hazelnut", type_id: 4},
  {tag: "cured meat", type_id: 1},
  {tag: "violet", type_id: 4},
  {tag: "lemongrass", type_id: 3},
  {tag: "clove", type_id: 3},
  {tag: "rose", type_id: 4},
  {tag: "majoram", type_id: 3},
  {tag: "licorice", type_id: 4},
  {tag: "dried thyme", type_id: 3},
  {tag: "lilac", type_id: 4},
  {tag: "sage", type_id: 3},
  {tag: "roasted meat", type_id: 1},
  {tag: "dried meat", type_id: 1},
  {tag: "beeswax", type_id: 1},
  {tag: "dark chocolate", type_id: 4},
  {tag: "milk chocolate", type_id: 4},
  {tag: "tarragon", type_id: 3},
  {tag: "balsamic", type_id: 4},
  {tag: "dried herbs", type_id: 3},
  {tag: "lager", type_id: 1},
  {tag: "fig", type_id: 4},
  {tag: "toffee", type_id: 4},
  {tag: "olive", type_id: 1},
  {tag: "olive oil", type_id: 1},
  {tag: "fennel", type_id: 1},
  {tag: "wet slate", type_id: 3},
  {tag: "seashell", type_id: 1},
  {tag: "dill", type_id: 1},
  {tag: "smoke", type_id: 1},
  {tag: "blackberry", type_id: 2},
  {tag: "cherry", type_id: 2},
  {tag: "black currant", type_id: 3},
  {tag: "apple", type_id: 2},
  {tag: "pineapple", type_id: 2},
  {tag: "plum", type_id: 2},
  {tag: "strawberry", type_id: 2},
  {tag: "raspberry", type_id: 2},
  {tag: "cream", type_id: 4},
  {tag: "crushed gravel", type_id: 3},
  {tag: "peach", type_id: 2},
  {tag: "watermelon", type_id: 2},
  {tag: "honeydew melon", type_id: 2},
  {tag: "pomegranate", type_id: 2},
  {tag: "black tea", type_id: 3},
  {tag: "pear", type_id: 2},
  {tag: "orange", type_id: 2},
  {tag: "lemon", type_id: 2},
  {tag: "lime", type_id: 2},
  {tag: "mango", type_id: 2},
  {tag: "geranium", type_id: 4},
  {tag: "blueberry", type_id: 4},
  {tag: "lemon curd", type_id: 3},
  {tag: "apricot", type_id: 2},
  {tag: "honey", type_id: 4},
  {tag: "tobacco", type_id: 3},
  {tag: "cinnamon", type_id: 3},
  {tag: "pear", type_id: 2},
  {tag: "gooseberry", type_id: 1}
])
WineTag.create!([
  {wine_id: 9, tag_id: 1},
  {wine_id: 9, tag_id: 1},
  {wine_id: 9, tag_id: 12},
  {wine_id: 9, tag_id: 10},
  {wine_id: 9, tag_id: 2},
  {wine_id: 9, tag_id: 11},
  {wine_id: 10, tag_id: 2},
  {wine_id: 10, tag_id: 8},
  {wine_id: 10, tag_id: 6},
  {wine_id: 10, tag_id: 22},
  {wine_id: 10, tag_id: 38},
  {wine_id: 11, tag_id: 1},
  {wine_id: 11, tag_id: 21},
  {wine_id: 11, tag_id: 34},
  {wine_id: 11, tag_id: 76},
  {wine_id: 11, tag_id: 77},
  {wine_id: 12, tag_id: 2},
  {wine_id: 12, tag_id: 11},
  {wine_id: 12, tag_id: 10},
  {wine_id: 12, tag_id: 52},
  {wine_id: 12, tag_id: 51},
  {wine_id: 12, tag_id: 77},
  {wine_id: 13, tag_id: 37},
  {wine_id: 13, tag_id: 23},
  {wine_id: 13, tag_id: 17},
  {wine_id: 13, tag_id: 78},
  {wine_id: 13, tag_id: 79},
  {wine_id: 14, tag_id: 21},
  {wine_id: 14, tag_id: 39},
  {wine_id: 15, tag_id: 39},
  {wine_id: 15, tag_id: 22},
  {wine_id: 15, tag_id: 21},
  {wine_id: 16, tag_id: 34},
  {wine_id: 16, tag_id: 24},
  {wine_id: 16, tag_id: 30},
  {wine_id: 16, tag_id: 54},
  {wine_id: 17, tag_id: 2},
  {wine_id: 17, tag_id: 3},
  {wine_id: 17, tag_id: 20},
  {wine_id: 17, tag_id: 20},
  {wine_id: 17, tag_id: 6},
  {wine_id: 18, tag_id: 3},
  {wine_id: 18, tag_id: 20},
  {wine_id: 18, tag_id: 67},
  {wine_id: 18, tag_id: 11},
  {wine_id: 18, tag_id: 41},
  {wine_id: 17, tag_id: 66},
  {wine_id: 19, tag_id: 3},
  {wine_id: 19, tag_id: 41},
  {wine_id: 19, tag_id: 1},
  {wine_id: 19, tag_id: 27},
  {wine_id: 19, tag_id: 78},
  {wine_id: 20, tag_id: 55},
  {wine_id: 20, tag_id: 17},
  {wine_id: 20, tag_id: 24},
  {wine_id: 21, tag_id: 17},
  {wine_id: 21, tag_id: 19},
  {wine_id: 21, tag_id: 6},
  {wine_id: 21, tag_id: 18},
  {wine_id: 22, tag_id: 54},
  {wine_id: 22, tag_id: 23},
  {wine_id: 22, tag_id: 24},
  {wine_id: 22, tag_id: 17},
  {wine_id: 22, tag_id: 25},
  {wine_id: 23, tag_id: 17},
  {wine_id: 23, tag_id: 73},
  {wine_id: 23, tag_id: 50},
  {wine_id: 24, tag_id: 50},
  {wine_id: 24, tag_id: 24},
  {wine_id: 24, tag_id: 25},
  {wine_id: 24, tag_id: 54},
  {wine_id: 25, tag_id: 1},
  {wine_id: 25, tag_id: 51},
  {wine_id: 25, tag_id: 33},
  {wine_id: 25, tag_id: 20},
  {wine_id: 25, tag_id: 27},
  {wine_id: 26, tag_id: 53},
  {wine_id: 26, tag_id: 70},
  {wine_id: 26, tag_id: 37},
  {wine_id: 26, tag_id: 31},
  {wine_id: 27, tag_id: 1},
  {wine_id: 27, tag_id: 33},
  {wine_id: 27, tag_id: 4},
  {wine_id: 27, tag_id: 42},
  {wine_id: 28, tag_id: 39},
  {wine_id: 28, tag_id: 74},
  {wine_id: 28, tag_id: 53},
  {wine_id: 29, tag_id: 21},
  {wine_id: 29, tag_id: 20},
  {wine_id: 29, tag_id: 67},
  {wine_id: 29, tag_id: 3},
  {wine_id: 29, tag_id: 78},
  {wine_id: 29, tag_id: 53},
  {wine_id: 30, tag_id: 34},
  {wine_id: 30, tag_id: 21},
  {wine_id: 30, tag_id: 65},
  {wine_id: 30, tag_id: 37},
  {wine_id: 31, tag_id: 25},
  {wine_id: 31, tag_id: 20},
  {wine_id: 31, tag_id: 80},
  {wine_id: 31, tag_id: 54},
  {wine_id: 32, tag_id: 54},
  {wine_id: 32, tag_id: 30},
  {wine_id: 32, tag_id: 27},
  {wine_id: 32, tag_id: 80},
  {wine_id: 33, tag_id: 18},
  {wine_id: 33, tag_id: 69},
  {wine_id: 33, tag_id: 72},
  {wine_id: 34, tag_id: 1},
  {wine_id: 34, tag_id: 4},
  {wine_id: 34, tag_id: 21},
  {wine_id: 35, tag_id: 53},
  {wine_id: 35, tag_id: 34},
  {wine_id: 35, tag_id: 31},
  {wine_id: 36, tag_id: 1},
  {wine_id: 36, tag_id: 51},
  {wine_id: 36, tag_id: 76},
  {wine_id: 36, tag_id: 6},
  {wine_id: 37, tag_id: 72},
  {wine_id: 37, tag_id: 6},
  {wine_id: 37, tag_id: 76},
  {wine_id: 38, tag_id: 55},
  {wine_id: 38, tag_id: 65},
  {wine_id: 38, tag_id: 65},
  {wine_id: 39, tag_id: 72},
  {wine_id: 39, tag_id: 49},
  {wine_id: 40, tag_id: 42},
  {wine_id: 40, tag_id: 30},
  {wine_id: 40, tag_id: 41},
  {wine_id: 40, tag_id: 1},
  {wine_id: 40, tag_id: 2},
  {wine_id: 41, tag_id: 2},
  {wine_id: 41, tag_id: 20},
  {wine_id: 41, tag_id: 52},
  {wine_id: 41, tag_id: 6},
  {wine_id: 41, tag_id: 78},
  {wine_id: 42, tag_id: 1},
  {wine_id: 42, tag_id: 47},
  {wine_id: 42, tag_id: 76},
  {wine_id: 42, tag_id: 51},
  {wine_id: 42, tag_id: 27},
  {wine_id: 43, tag_id: 20},
  {wine_id: 43, tag_id: 1},
  {wine_id: 43, tag_id: 12},
  {wine_id: 43, tag_id: 43},
  {wine_id: 44, tag_id: 80},
  {wine_id: 44, tag_id: 54},
  {wine_id: 44, tag_id: 53},
  {wine_id: 45, tag_id: 2},
  {wine_id: 45, tag_id: 39},
  {wine_id: 45, tag_id: 3},
  {wine_id: 45, tag_id: 41},
  {wine_id: 46, tag_id: 46},
  {wine_id: 46, tag_id: 33},
  {wine_id: 46, tag_id: 20},
  {wine_id: 46, tag_id: 2},
  {wine_id: 47, tag_id: 20},
  {wine_id: 47, tag_id: 27},
  {wine_id: 47, tag_id: 68},
  {wine_id: 47, tag_id: 51},
  {wine_id: 48, tag_id: 24},
  {wine_id: 48, tag_id: 34},
  {wine_id: 48, tag_id: 80},
  {wine_id: 48, tag_id: 30},
  {wine_id: 49, tag_id: 24},
  {wine_id: 49, tag_id: 30},
  {wine_id: 50, tag_id: 2},
  {wine_id: 50, tag_id: 1},
  {wine_id: 50, tag_id: 5},
  {wine_id: 50, tag_id: 55},
  {wine_id: 50, tag_id: 47},
  {wine_id: 51, tag_id: 52},
  {wine_id: 51, tag_id: 77},
  {wine_id: 52, tag_id: 12},
  {wine_id: 52, tag_id: 22},
  {wine_id: 53, tag_id: 27},
  {wine_id: 53, tag_id: 67},
  {wine_id: 53, tag_id: 39},
  {wine_id: 54, tag_id: 55},
  {wine_id: 54, tag_id: 17},
  {wine_id: 54, tag_id: 49},
  {wine_id: 55, tag_id: 2},
  {wine_id: 55, tag_id: 75},
  {wine_id: 56, tag_id: 72},
  {wine_id: 56, tag_id: 37},
  {wine_id: 56, tag_id: 71},
  {wine_id: 57, tag_id: 54},
  {wine_id: 57, tag_id: 49},
  {wine_id: 58, tag_id: 24},
  {wine_id: 59, tag_id: 68},
  {wine_id: 59, tag_id: 20},
  {wine_id: 59, tag_id: 52},
  {wine_id: 60, tag_id: 20},
  {wine_id: 60, tag_id: 41},
  {wine_id: 60, tag_id: 67},
  {wine_id: 60, tag_id: 11},
  {wine_id: 61, tag_id: 64},
  {wine_id: 61, tag_id: 54},
  {wine_id: 61, tag_id: 34},
  {wine_id: 62, tag_id: 17},
  {wine_id: 62, tag_id: 65},
  {wine_id: 63, tag_id: 27},
  {wine_id: 63, tag_id: 27},
  {wine_id: 63, tag_id: 24},
  {wine_id: 63, tag_id: 77},
  {wine_id: 64, tag_id: 37},
  {wine_id: 64, tag_id: 55},
  {wine_id: 65, tag_id: 69},
  {wine_id: 65, tag_id: 61},
  {wine_id: 66, tag_id: 55},
  {wine_id: 66, tag_id: 24},
  {wine_id: 67, tag_id: 17},
  {wine_id: 67, tag_id: 54},
  {wine_id: 68, tag_id: 24},
  {wine_id: 68, tag_id: 59},
  {wine_id: 68, tag_id: 58},
  {wine_id: 9, tag_id: 1},
  {wine_id: 9, tag_id: 11},
  {wine_id: 9, tag_id: 12},
  {wine_id: 9, tag_id: 10},
  {wine_id: 70, tag_id: 56},
  {wine_id: 70, tag_id: 39},
  {wine_id: 70, tag_id: 53},
  {wine_id: 71, tag_id: 76},
  {wine_id: 71, tag_id: 21},
  {wine_id: 71, tag_id: 1},
  {wine_id: 71, tag_id: 77},
  {wine_id: 71, tag_id: 77},
  {wine_id: 72, tag_id: 2},
  {wine_id: 72, tag_id: 22},
  {wine_id: 72, tag_id: 27},
  {wine_id: 72, tag_id: 52}
])
Type.create!([
  {name: "funky"},
  {name: "fruity"},
  {name: "earthy"},
  {name: "sweet"}
])
Rating.create!([
  {rating: "4.2", notes: "plum, black cherry, tart acidity, grippy tannins, smooth long finish", vintner: "waxed bat, malbec, cabernet sauvingon, merlot blend 2019", user_id: nil, wine_id: nil},
  {rating: "4.0", notes: "not really a wine, a malt liquor ... for refined pallets only", vintner: "mad dog ", user_id: nil, wine_id: nil},
  {rating: "4.0", notes: "great", vintner: "boones farm", user_id: nil, wine_id: nil},
  {rating: "4.0", notes: "sparkling white", vintner: "roederrer estates", user_id: nil, wine_id: nil},
  {rating: "4.0", notes: "sparkling white", vintner: "roederrer estates", user_id: nil, wine_id: nil},
  {rating: "3.4", notes: "Strawberry, cranberry, grapefruit. Well balanced acidity. Bright and fresh. Nothing special but great french rose for the price", vintner: "Mas Fleurey Rose, Cotes de Provence", user_id: 1, wine_id: nil},
  {rating: "5.0", notes: "Light, crisp red apples with hints of vanilla and toast. Bright acidity and delicate bubbles. Finishes pleasantly. Perfect Spanish Cava for summer!", vintner: "Spanish Cava", user_id: nil, wine_id: nil},
  {rating: "1.0", notes: "my grandpa says this is a great wine", vintner: "winking owl ", user_id: 8, wine_id: nil},
  {rating: "3.4", notes: "Red Cherry on the nose with pepper. Hints of licorice with a chocolate finish. Mid sweetness. Needed a bit more acidity ", vintner: "zweigelt", user_id: 8, wine_id: nil},
  {rating: "3.5", notes: "lacking body and some character but really good bordeaux for the price point. hints of smoke and tart cherry", vintner: "Château la Gabarre Bordeaux Supérieur 2015", user_id: 9, wine_id: nil},
  {rating: "3.4", notes: "Seems ok at the start but wears off as you drink it. Super light Zin, almost Pinot-like with a juicy cherry flavor and a bite on the finish. Not my favorite.", vintner: "League of Rogues Rapscallion Zinfandel 2016 ", user_id: 9, wine_id: nil},
  {rating: "4.1", notes: "Black cherry forward, hearty body, with a nice oaky dry finish makes this an ideal picnic wine - cheese and charcuterie pair superbly. Caseworthy.", vintner: "Babylon's Peak Apeloko Pinotage 2018", user_id: 9, wine_id: nil},
  {rating: "5.0", notes: "My favorite California Cab... I love the blackberry and menthol on the nose with a hint of leather to round out the sweet blackberry. perfectly balanced acidity and grippy tannin. tons of character. ", vintner: "Heitz Cellar Bella Oaks Vineyard Cabernet Sauvignon 2009", user_id: 9, wine_id: nil},
  {rating: "4.8", notes: "Perfect Montalcino. Starts with red cherry and vanilla on the nose with vanilla. Earthy and complex, the perfect Montalcino for entertaining wine enthusiasts", vintner: "Abbadia Ardenga Brunello di Montalcino 2012", user_id: 9, wine_id: nil},
  {rating: "3.6", notes: "Light salmon in color, soft strawberries and citrus notes. Light acidity, tastes like it smells. Good patio sipping and with food. Would enjoy this again.", vintner: " Aime Roquesante Mas Fleurey Cuvée Selectionnée Côtes de Provence 2019", user_id: 9, wine_id: nil},
  {rating: "3.1", notes: "Dried fruit, red fruit, dark fruit, cocoa, mild smoke, pepper. Medium body, dry finish.", vintner: " Voyage Cabernet Sauvignon 2018", user_id: 9, wine_id: nil},
  {rating: nil, notes: "", vintner: "bordeaux", user_id: 12, wine_id: nil},
  {rating: nil, notes: "", vintner: "tempranillo", user_id: 12, wine_id: nil},
  {rating: "4.0", notes: "great balanced acidity cherry on the nose", vintner: "pinot noir josh cellars -2015", user_id: 12, wine_id: nil},
  {rating: "4.0", notes: "muito bem", vintner: "tempranillo", user_id: 14, wine_id: nil},
  {rating: "4.0", notes: "some detailed tasting notes", vintner: "nebbiolo-vintner 2015-", user_id: 9, wine_id: nil}
])
Wine.create!([
  {varietal: "Verdejo", color: "white"},
  {varietal: "Vermentino", color: "white"},
  {varietal: "Vinho Verde", color: "white"},
  {varietal: "Pinot Noir", color: "red"},
  {varietal: "Zinfandel", color: "red"},
  {varietal: "Bordeaux", color: "red"},
  {varietal: "Prosecco", color: "bubbly-white"},
  {varietal: "Rose", color: "rose"},
  {varietal: "Pinot Grigio", color: "white"},
  {varietal: "Rioja", color: "red"},
  {varietal: "Tempranillo", color: "red"},
  {varietal: "Barbera", color: "red"},
  {varietal: "Cava", color: "bubbly-white"},
  {varietal: "Chardonnay", color: "white"},
  {varietal: "Champagne", color: "bubbly-white"},
  {varietal: "Chenin Blanc", color: "white"},
  {varietal: "Crémant", color: "white"},
  {varietal: "Dolcetto", color: "red"},
  {varietal: "Fiano", color: "white"},
  {varietal: "Gamay", color: "red"},
  {varietal: "Gewürzstraminer", color: "white"},
  {varietal: "Grenache", color: "red"},
  {varietal: "Grachetto", color: "white"},
  {varietal: "Grenache blanc", color: "white"},
  {varietal: "Grüner Veltliner", color: "white"},
  {varietal: "Ice Wine", color: "dessert"},
  {varietal: "Lambrusco", color: "red"},
  {varietal: "Madeira", color: "red"},
  {varietal: "Malbec", color: "red"},
  {varietal: "Vin Santo", color: "dessert"},
  {varietal: "Cabernet Sauvignon", color: "red"},
  {varietal: "Marsala", color: "dessert"},
  {varietal: "Melon", color: "white"},
  {varietal: "Marsanne", color: "white"},
  {varietal: "Mencía", color: "red"},
  {varietal: "Merlot", color: "red"},
  {varietal: "Monastrell", color: "red"},
  {varietal: "Montapulciano", color: "red"},
  {varietal: "Muscat Blanc", color: "white"},
  {varietal: "Nebbiolo", color: "red"},
  {varietal: "Petite Verdot", color: "red"},
  {varietal: "Petite Sirah", color: "red"},
  {varietal: "Pinot Blanc", color: "white"},
  {varietal: "Pinot Gris", color: "white"},
  {varietal: "Pinotage", color: "red"},
  {varietal: "Port", color: "dessert"},
  {varietal: "Rhône / GSM Blend", color: "red"},
  {varietal: "Mourvédre", color: "red"},
  {varietal: "Riesling", color: "white"},
  {varietal: "Sangiovese", color: "red"},
  {varietal: "Sauvignon Blanc", color: "white"},
  {varietal: "Sémillon", color: "white"},
  {varietal: "Sherry", color: "dessert"},
  {varietal: "Syrah", color: "red"},
  {varietal: "Tannat", color: "red"},
  {varietal: "Torrontés", color: "white"},
  {varietal: "Trebbiano Toscano", color: "white"},
  {varietal: "Valpolicella Blend", color: "red"},
  {varietal: "Verdicchio", color: "white"},
  {varietal: "Cabernet Sauvignon", color: "red"},
  {varietal: "Viognier", color: "white"},
  {varietal: "Zinfandel", color: "red"},
  {varietal: "Zweigelt", color: "red"},
  {varietal: "Sparkling Rose", color: "bubbly-rose"}
])
User.create!([
  {first_name: "Melanie", last_name: "Crawford", email: "crawdaddy@hotmale.com", password_digest: nil},
  {first_name: "Andy", last_name: "Greggor", email: "mcgreggor@yahoo.com", password_digest: nil},
  {first_name: "Marie", last_name: "Bucol", email: "conductor@akron.edu", password_digest: nil},
  {first_name: "Jules", last_name: "Chan", email: "brainsnstuff@akronchildrens.com", password_digest: nil},
  {first_name: "Melanie", last_name: "Grigger", email: "melanie.grigger@gmail.com", password_digest: "$2a$12$yfBNnBcMGAEcUCQyeF5mg.yST5G1EL3wQdyfo8PhygeH79DvtZsyS"},
  {first_name: "Andy", last_name: "Grigger", email: "andy.grigger@gmail.com", password_digest: "$2a$12$ZtgYVGDnDpL7BL2hqxtHL.cQY9xX/ZImMLNADASVcLyw.Uuou8El2"},
  {first_name: "Sally", last_name: "Snail", email: "sally@gmail.com", password_digest: "$2a$12$Q/nBmoYDCeNqsPHoJew8N.TnyN2wNxIOeQ8VOhRyGhtqYc/vJh2XC"},
  {first_name: "Koen", last_name: "Alan", email: "koen@gmail.com", password_digest: "$2a$12$KIxOWeRFv74z4veU7SG7ae0J.L9YZAsv48jEfBjlEUdgJl3QI2WlK"},
  {first_name: nil, last_name: nil, email: "crawford@grigger.com", password_digest: "$2a$12$Vu8s9LjoBhtCghUPkmRTqeiP01EJVZ1WdwdRuiQzWTM5Pat1lB5VG"},
  {first_name: nil, last_name: nil, email: "danimal@gmail.com", password_digest: "$2a$12$yvLKYREUuHH.CxNC1Xk6f.hEJI7Nd6pnhiaxWvz6U0FRceKaYr.xK"},
  {first_name: nil, last_name: nil, email: "bubbles@hotmale.com", password_digest: "$2a$12$1P4LlqAcSDJeCbO8Ske7zOLduTJ9TuL4zNq/1zAeTE1V6hMImUpFi"},
  {first_name: nil, last_name: nil, email: "lolie@gmail.com", password_digest: "$2a$12$2AtgkOCunjY0I1Y/Cwl.Nu49siGQSQm/J57qNhp9FSUjnfvZ2AH3G"},
  {first_name: nil, last_name: nil, email: "vino@gmail.com", password_digest: "$2a$12$qqcT.SASIBQiUSJHP7UWe.n2VuXjeskaJ.Z0XEVZdw/0.DbLAy56G"},
  {first_name: nil, last_name: nil, email: "koen@helpme.com", password_digest: "$2a$12$4WHUWXh7kDJBnJgyxteIw.4t..jrhlMyQz1ntGGXPI9ieHabsxgDm"}
])
